### ISSUE TITLE
问题反馈建议

### ISSUE THREAD

**Issue by mrzhaoyw** [Jason-wam/Cat-Maven-2023#1]
发现页不能打开了  另外希望能把预览的图片和信息弄的大一点  介绍全面一点 能给播放器多加一些功能 比如调整清晰度 饱和度什么的

**Comment by Jason-wam** [comment]
资源都是从网络搜索，并不能控制具体显示内容，清晰度什么的更不用考虑

**Comment by cjz-com** [comment]
大佬，可以做个电视版不？
