### ISSUE TITLE
横屏播放时通过点下一集按钮切换剧集的播放进度不会被记录

### ISSUE THREAD

**Issue by lumingzh** [Jason-wam/Cat-Maven-2023#13]
如题，横屏状态播放剧集，通过点下一集按钮观看多集后返回并退出视频详情页，重新进入视频详情页会发现播放记录仍为第一次播放时的集数，只有在视频详情页手动点选集数的行为才会被软件记录。

**Comment by Jason-wam** [comment]
好的，等待修复。
