### ISSUE TITLE
插播广告时视频会自动快进

### ISSUE THREAD

**Issue by lumingzh** [Jason-wam/Cat-Maven-2023#14]
如题，插播广告时有两个问题：
- 视频卡顿，甚至有概率会画面一直卡在卡顿时的一帧但音频播放正常（手动快进快退会恢复）
- 广告出现前的一瞬间视频会自动快进一大截，然后出现第一种问题，根据插播时的视频播放进度甚至能直接快进到片尾曲

不知道广告插播的原理是啥，如果是原视频就有的那不应该会出现这些问题，如果是外挂插播的那为啥会完美契合进度时间轴，是否能通过插播广告前先强行暂停视频播放，广告后自动继续播放的方式解决这些问题呢？谢谢。

**Comment by Jason-wam** [comment]
应该是视频源的问题，尝试换源解决

**Comment by lumingzh** [comment]
试了一下其它视频源，确实不是软件的问题。
