### ISSUE TITLE
tv不能全屏，tab没有选中状态

### ISSUE THREAD

**Issue by linzzzzllll** [Jason-wam/Cat-Maven-2023#17]
tv不能全屏，tab没有选中状态

**Comment by Jason-wam** [comment]
软件目前并不适配tv喔

**Comment by linzzzzllll** [comment]
> 软件目前并不适配tv喔

软件自适应做的挺好的,我都以为是tv有适配

**Comment by Jason-wam** [comment]
> > 软件目前并不适配tv喔
> 
> 软件自适应做的挺好的,我都以为是tv有适配

以后有时间会出tv版的

**Comment by linzzzzllll** [comment]
> > > 软件目前并不适配tv喔
> > 
> > 
> > 软件自适应做的挺好的,我都以为是tv有适配
> 
> 以后有时间会出tv版的

其实用安卓的也没什么问题,就是我上面的 2 个小问题.估计是没适配遥控器,用鼠标就能滑过去点到全屏的按钮遥控器就按不过去.我是在电视应用推荐里看到 的这个应用

**Comment by Jason-wam** [comment]
> > > > 软件目前并不适配tv喔
> > > 
> > > 
> > > 软件自适应做的挺好的,我都以为是tv有适配
> > 
> > 
> > 以后有时间会出tv版的
> 
> 其实用安卓的也没什么问题,就是我上面的 2 个小问题.估计是没适配遥控器,用鼠标就能滑过去点到全屏的按钮遥控器就按不过去.我是在电视应用推荐里看到 的这个应用

确实是这样的，电视端需要单独对遥控的焦点进行适配
