### ISSUE TITLE
播放视频越快越好的问题越快越好修复

### ISSUE THREAD

**Issue by cglghf** [Jason-wam/Cat-Maven-2023#18]

**Comment by cglghf** [comment]
我希望资源猫越来越好

**Comment by cglghf** [comment]
播放线路不卡不慢播放时间越快越好

**Comment by Jason-wam** [comment]
什么意思

**Comment by Jason-wam** [comment]
> 播放线路不卡不慢播放时间越快越好

什么意思

**Comment by cglghf** [comment]
> > 播放线路不卡不慢播放时间越快越好
> 
> 什么意思

因为播放的时候总是卡顿

**Comment by cglghf** [comment]
> _No description provided._

因为播放的时候总是卡顿

**Comment by Jason-wam** [comment]
> > > 播放线路不卡不慢播放时间越快越好
> > 
> > 什么意思
> 
> 因为播放的时候总是卡顿有一些视频老是播放不了

等新版可能会好点

**Comment by cglghf** [comment]
播放的时候为什么老是显示出出了点小问题，请稍后重试
