### ISSUE TITLE
搜索功能优化

### ISSUE THREAD

**Issue by Vogadero** [Jason-wam/Cat-Maven-2023#2]
点击搜索进去以后，输入文字中间页的显示是空的，这样很不友好，其实搜索框放上面很不错的，放下面有点不太爽的感觉，大部分人会下意识点上面，但是却点不进去![Screenshot_20230521-113011.jpg](https://github.com/Jason-wam/Cat-Maven-2023/assets/30587603/0169596f-1207-4b95-9b0e-22a6c2ad0f9a)

**Comment by Jason-wam** [comment]
疑似手机适配问题，搜索框未能正确悬浮，手机是什么型号

**Comment by Vogadero** [comment]
> 疑似手机适配问题，搜索框未能正确悬浮，手机是什么型号
> 
> 疑似手机适配问题，搜索框未能正确悬浮，手机是什么型号

很老的手机，一加5😂
