### ISSUE TITLE
淘劵的问题

### ISSUE THREAD

**Issue by cglghf** [Jason-wam/Cat-Maven-2023#25]
无法打开淘劵
![Screenshot_20240319_174501](https://github.com/Jason-wam/Cat-Maven-2023/assets/158288711/ec74512f-94b7-492c-b311-d38e324dc85f)

**Comment by Jason-wam** [comment]
已经知道了，等待修复喔

**Comment by cglghf** [comment]
> 已经知道了，等待修复喔

什么时候修复
