### ISSUE TITLE
缓存到本地的视频支持投屏的话就更好了

### ISSUE THREAD

**Issue by meiMingle** [Jason-wam/Cat-Maven-2023#26]

**Comment by Jason-wam** [comment]
这个无法实现喔

**Comment by meiMingle** [comment]
建议尝试做一下这个功能，现在这些资源网站严重限速，直接投屏一卡一卡的。如果能把视频缓存后再进行投屏将大大改善使用体验。

**Comment by meiMingle** [comment]
目前我临时的解决方案就是使用1DM下载视频，然后通过第三方视频软件投屏，比如XPlayer进行投屏播放，勉强能用就是麻烦，得多下载两个软件

**Comment by Jason-wam** [comment]
内置缓存功能因文件格式原因无法实现投屏，不过可以通过使用安卓系统自带的投屏[Cast功能进行投屏播放]
