### ISSUE TITLE
资源猫HD版本的广告展示问题

### ISSUE THREAD

**Issue by ling157915** [Jason-wam/Cat-Maven-2023#27]
资源猫HD版本的广告展示问题。安装在华为智慧屏（电视）上以后，打开软件时有一个倒计时的广告是有倒计时的，可以自动关闭。但是选中某一个影片，观看前的的广告只有×，没有倒计时，电视遥控无法关闭此广告，因而造成无法观看。
![1712536055200](https://github.com/Jason-wam/Cat-Maven-2023/assets/166345146/6b764c67-0099-4092-8768-b91cb9b349ca)

**Comment by ling157915** [comment]
希望这个界面的广告可以加入倒计时，让其自动关闭。

**Comment by Jason-wam** [comment]
软件并不适配电视
