### ISSUE TITLE
我想帮着推广出去不知道可否

### ISSUE THREAD

**Issue by SANSHENSS** [Jason-wam/Cat-Maven-2023#34]
你好，见字安：
       我自己就是APP深度使用者，我想把APP推广出去，用线下的方式。不知道是否会冒犯，特来请示。如有不妥之处请指出。若有可能可否合作一波。

**Comment by Jason-wam** [comment]
可以的，没问题

**Comment by SANSHENSS** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by SANSHENSS** [comment]
有没有微信或者邮箱，这个着实有些不便

**Comment by Jason-wam** [comment]
> 有没有微信或者邮箱，这个着实有些不便

无

**Comment by SANSHENSS** [comment]
可以给到专有的邀请码么？如果我线下推广的话

**Comment by Jason-wam** [comment]
> 可以给到专有的邀请码么？如果我线下推广的话

不需要邀请码呀，分享二维码即可![share_video_cat_1714269836761.jpg](https://github.com/Jason-wam/Cat-Maven-2023/assets/48165620/e23d81b1-a262-4280-bfeb-17e8a1666c54)

**Comment by SANSHENSS** [comment]
可是这样我不就不知道谁是我推荐下载的

**Comment by Jason-wam** [comment]
> 可是这样我不就不知道谁是我推荐下载的

软件没有邀请码这个功能喔

**Comment by Jason-wam** [comment]
> 可是这样我不就不知道谁是我推荐下载的

你可自行建群，自己存网盘
