### ISSUE TITLE
下一集按钮点不动

### ISSUE THREAD

**Issue by csw1053541731** [Jason-wam/Cat-Maven-2023#37]
感谢作者，这个软件非常好！但是发现这个下一集按钮点不动，不知道是否有问题？
![IMG_20240510_214941](https://github.com/Jason-wam/Cat-Maven-2023/assets/121945199/a14c31cc-441b-49bf-bc51-5c76b66942a6)

**Comment by Jason-wam** [comment]
注意看视频类型，在线播放的才支持自动下一集喔，建议反馈时截个图的哈
