### ISSUE TITLE
平台问题

### ISSUE THREAD

**Issue by yang18608706912** [Jason-wam/Cat-Maven-2023#40]
我想有个问题想提问一下，蓝奏云网盘是什么，如果下载 APP 成为会员，为什么非会员不支持分享文件了，要收费了？？

**Comment by Jason-wam** [comment]
并不需要开会员，蓝奏云的迷惑操作，可以把浏览器ua改成pc的，等我抽空换个网盘![mmexport1715783509287.jpg](https://github.com/Jason-wam/Cat-Maven-2023/assets/48165620/bba9854a-bdaf-4a53-9d6c-bfc41fe47e8d)

**Comment by Jason-wam** [comment]
[资源猫2024 - 3.0.5](https://github.com/Jason-wam/Cat-Maven-2023/blob/main/%E5%AE%89%E8%A3%85%E5%8C%85/%E8%B5%84%E6%BA%90%E7%8C%AB2024%20-%203.0.5.apk)

**Comment by Jason-wam** [comment]
[资源猫2024 - 3.0.5 123云盘](https://www.123pan.com/s/n8kKVv-LfPkv.html)
