### ISSUE TITLE
无法打开片库的问题

### ISSUE THREAD

**Issue by cglghf** [Jason-wam/Cat-Maven-2023#47]
![Screenshot_20240604_102355](https://github.com/Jason-wam/Cat-Maven-2023/assets/158288711/fe487092-cb6e-4427-95f1-bb36da4cf7b2)
无法打开片库

**Comment by Jason-wam** [comment]
> ![Screenshot_20240604_102355](https://github.com/Jason-wam/Cat-Maven-2023/assets/158288711/fe487092-cb6e-4427-95f1-bb36da4cf7b2)
> 无法打开片库

看到了，等待修复

**Comment by Jason-wam** [comment]
现在是否可以了

**Comment by cglghf** [comment]
> 现在是否可以了

可以打开
