### ISSUE TITLE
软件出现已崩溃问题。

### ISSUE THREAD

**Issue by yang18608706912** [Jason-wam/Cat-Maven-2023#51]
刚更新的 3.0.6 的版本后，打开软件搜索影视名称就崩溃了，无法搜索了。
![Screenshot_2024-07-03-16-34-22-892_com walixiwa flash player](https://github.com/Jason-wam/Cat-Maven-2023/assets/168715782/c51ba755-8a90-450b-9814-3b13f6f96dd3)

**Comment by Jason-wam** [comment]
收到，正在修复

**Comment by Jason-wam** [comment]
已修复 [资源猫2024 - 3.0.7](https://xswl.lanzn.com/iXyYW23f5xaj)
