### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by yang18608706912** [Jason-wam/Cat-Maven-2023#53]
现在打开 3.0.6 的版本还是没有收到 3.0.7 版本的更新提示，设置检查更新也没有提示。

**Comment by Jason-wam** [comment]
> 现在打开 3.0.6 的版本还是没有收到 3.0.7 版本的更新提示，设置检查更新也没有提示。

> 设置，清除缓存呢，还有，不要每次都重新开issues，继续之前的即可
