### ISSUE TITLE
病毒什么时候去一下

### ISSUE THREAD

**Issue by shenfangda520** [Jason-wam/Cat-Maven-2023#56]
病毒一直报你们不去一下？还是让举报

**Comment by Jason-wam** [comment]
软件哪有病毒啊？？？？！

**Comment by Jason-wam** [comment]
这类软件报毒很正常，如果介意的话可以不用的，

**Comment by Jason-wam** [comment]
![QQ20240704-163028](https://github.com/Jason-wam/Cat-Maven-2023/assets/48165620/43537ce1-9594-4d6d-8219-b706b2a93d04)

没听说过

**Comment by shenfangda520** [comment]
我推荐好多朋友用咱们软件好几个手机都提前有病毒，其实我也不知道是啥那个，广告没啥就是这个病毒提示有点害怕，我是加入白名单了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 面条君 ***@***.***&gt;
发送时间: 2024年7月4日 16:31
收件人: 964003502 ***@***.***&gt;
主题: Re: [Jason-wam/Cat-Maven-2023] 病毒什么时候去一下 (Issue #56)





 
QQ20240704-163028.png (view on web)
 
没听说过

**Comment by Jason-wam** [comment]
没上架的软件很容易报毒的，建议添加信任，我们这边也没有办法，小米手机上是正常的

**Comment by shenfangda520** [comment]
这个不清楚但是其他来源软件并不报病毒



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 面条君 ***@***.***&gt;
发送时间: 2024年7月4日 16:36
收件人: Jason-wam/Cat-Maven-2023 ***@***.***&gt;
抄送: 申方达 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Jason-wam/Cat-Maven-2023] 病毒什么时候去一下 (Issue #56)





  
我推荐好多朋友用咱们软件好几个手机都提前有病毒，其实我也不知道是啥那个，广告没啥就是这个病毒提示有点害怕，我是加入白名单了 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: 面条君 @.&gt; 发送时间: 2024年7月4日 16:31 收件人: 964003502 @.&gt; 主题: Re: [Jason-wam/Cat-Maven-2023] 病毒什么时候去一下 (Issue #56) QQ20240704-163028.png (view on web) 没听说过 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
这是手机厂商的问题，没发现现在安装软件都很麻烦吗

**Comment by shenfangda520** [comment]
我已经填白名单里面了，我是帮朋友们咨询一下你们，我都用了好几年了，一路陪伴来的





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 面条君 ***@***.***&gt;
发送时间: 2024年7月4日 16:37
收件人: 964003502 ***@***.***&gt;
主题: Re: [Jason-wam/Cat-Maven-2023] 病毒什么时候去一下 (Issue #56)





 
没上架的软件很容易报毒的，建议添加信任，我们这边也没有办法，小米手机上是正常的

**Comment by Jason-wam** [comment]
> 这个不清楚但是其他来源软件并不报病毒 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 面条君 ***@***.***&gt; 发送时间: 2024年7月4日 16:36 收件人: Jason-wam/Cat-Maven-2023 ***@***.***&gt; 抄送: 申方达 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [Jason-wam/Cat-Maven-2023] 病毒什么时候去一下 (Issue #56) 我推荐好多朋友用咱们软件好几个手机都提前有病毒，其实我也不知道是啥那个，广告没啥就是这个病毒提示有点害怕，我是加入白名单了 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: 面条君 @.&gt; 发送时间: 2024年7月4日 16:31 收件人: 964003502 @.&gt; 主题: Re: [Jason-wam/Cat-Maven-2023] 病毒什么时候去一下 (Issue #56) QQ20240704-163028.png (view on web) 没听说过 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 这是手机厂商的问题，没发现现在安装软件都很麻烦吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你那边是什么机型，对于这种问题我们没什么好办法

**Comment by shenfangda520** [comment]
Realme &nbsp;oppo



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 面条君 ***@***.***&gt;
发送时间: 2024年7月4日 16:39
收件人: Jason-wam/Cat-Maven-2023 ***@***.***&gt;
抄送: 申方达 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Jason-wam/Cat-Maven-2023] 病毒什么时候去一下 (Issue #56)





  
这个不清楚但是其他来源软件并不报病毒 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: 面条君 @.&gt; 发送时间: 2024年7月4日 16:36 收件人: Jason-wam/Cat-Maven-2023 @.&gt; 抄送: 申方达 @.&gt;, Author @.&gt; 主题: Re: [Jason-wam/Cat-Maven-2023] 病毒什么时候去一下 (Issue #56) 我推荐好多朋友用咱们软件好几个手机都提前有病毒，其实我也不知道是啥那个，广告没啥就是这个病毒提示有点害怕，我是加入白名单了 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: 面条君 @.&gt; 发送时间: 2024年7月4日 16:31 收件人: 964003502 @.&gt; 主题: Re: [Jason-wam/Cat-Maven-2023] 病毒什么时候去一下 (Issue #56) QQ20240704-163028.png (view on web) 没听说过 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 这是手机厂商的问题，没发现现在安装软件都很麻烦吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
你那边是什么机型，对于这种问题我们没什么好办法

**Comment by Jason-wam** [comment]
> oppo

我这只有一加，coloros系统，目前测试是没问题的，添加信任吧，相信资源猫😊

**Comment by shenfangda520** [comment]
那肯定信你们只能添加到白名单里面，不添加好多app提示病毒



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 面条君 ***@***.***&gt;
发送时间: 2024年7月4日 16:42
收件人: Jason-wam/Cat-Maven-2023 ***@***.***&gt;
抄送: 申方达 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Jason-wam/Cat-Maven-2023] 病毒什么时候去一下 (Issue #56)





  
oppo
  
我这只有一加，coloros系统，目前测试是没问题的，添加信任吧，相信资源猫😊

**Comment by Jason-wam** [comment]
FileRepMalware [Trj] - 【文件信誉病毒】，说白了就是系统不信任这类软件，放心用就好了，安卓端不存在所谓的病毒，最多也就是流氓软件。

**Comment by shenfangda520** [comment]
哈哈哈，对



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 面条君 ***@***.***&gt;
发送时间: 2024年7月4日 16:46
收件人: Jason-wam/Cat-Maven-2023 ***@***.***&gt;
抄送: 申方达 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Jason-wam/Cat-Maven-2023] 病毒什么时候去一下 (Issue #56)





 
FileRepMalware [Trj] - 【文件信誉病毒】，说白了就是系统不信任这类软件，放心用就好了，安卓端不存在所谓的病毒，最多也就是流氓软件。
