### ISSUE TITLE
软件卡顿问题

### ISSUE THREAD

**Issue by yang18608706912** [Jason-wam/Cat-Maven-2023#57]
你好，你这个 3.0.8 版本更新后有卡顿现象，把任意资源网打开之后，点集数播放的时候会卡顿，没有响应的现象出现，你看可以修复下卡顿的这个问题。谢谢

**Comment by Jason-wam** [comment]
> 你好，你这个 3.0.8 版本更新后有卡顿现象，把任意资源网打开之后，点集数播放的时候会卡顿，没有响应的现象出现，你看可以修复下卡顿的这个问题。谢谢

可以正常播放吗

**Comment by Jason-wam** [comment]
尝试卸载重新安装哦，这次不同时间推送了两个版本，可能之前的代码有点问题，试试这个 [资源猫2024 - 3.0.8.apk](https://xswl.lanzn.com/izMIb23iawvc)

**Comment by qzdxj** [comment]
下载后的文件目录是什么

**Comment by Jason-wam** [comment]
> 下载后的文件目录是什么

是特殊的缓存文件格式，找到也没用
