### ISSUE TITLE
电视没法全屏，希望开发个电视端

### ISSUE THREAD

**Issue by mourenqiao** [Jason-wam/Cat-Maven-2023#59]
![1721189673957](https://github.com/user-attachments/assets/28d6081c-4a80-485f-8d87-0f7902dbf741)

**Comment by Jason-wam** [comment]
暂无这个打算，建议用投屏

**Comment by Jason-wam** [comment]
可以用安卓自带的屏幕投射功能，效果更好

**Comment by mourenqiao** [comment]
将【快退】【播放】【快进】【清晰度切换】【全屏】这些按钮添加到播放屏幕区域的下方会更好，电视端。不知道为什么电视调用不出来





来自阿里邮箱Android客户端------------------------------------------------------------------
***@***.***>
日　期：2024年07月18日 16:27:16
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [Jason-wam/Cat-Maven-2023] 电视没法全屏，希望开发个电视端 (Issue #59)

暂无这个打算，建议用投屏

**Comment by mourenqiao** [comment]
电视也是apk文件，功能都有了，调整一下界面布局就可以适用平板/电视端





来自阿里邮箱Android客户端------------------------------------------------------------------
***@***.***>
日　期：2024年07月18日 16:27:59
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [Jason-wam/Cat-Maven-2023] 电视没法全屏，希望开发个电视端 (Issue #59)

可以用安卓自带的屏幕投射功能，效果更好
