### ISSUE TITLE
更新后历史记录没有了

### ISSUE THREAD

**Issue by 130252251** [Jason-wam/Cat-Maven-2023#6]
![Screenshot_2023-06-06-15-26-41-30_dc023e1ee15c0617900ad5de029f9f50](https://github.com/Jason-wam/Cat-Maven-2023/assets/75723161/508dcaf3-fef2-4c74-8629-4ea994171a0b)
![Screenshot_2023-06-06-15-26-44-68_dc023e1ee15c0617900ad5de029f9f50](https://github.com/Jason-wam/Cat-Maven-2023/assets/75723161/77c3dd49-b473-4e2f-9800-634aa7c741aa)
更新后，显示的有20个历史记录，但点开里面都没有了，下次更新后会不会还这样没有历史记录？那很伤。。

**Comment by Jason-wam** [comment]
下次不会再出现这个问题了，清空一下
