### ISSUE TITLE
站内资源网失效问题

### ISSUE THREAD

**Issue by yang18608706912** [Jason-wam/Cat-Maven-2023#67]
站源资源网又失效了，怎么回事呢，是否可以更新修复站源资源网这个问题。

**Comment by Jason-wam** [comment]
什么意思，搜索不到还是什么问题，请详细描述

**Comment by yang18608706912** [comment]
就是某些个别资源网失效了，没有，搜索不到这个资源网。这是第三方的问题，还是你这边可以修复的资源网？

**Comment by Jason-wam** [comment]
> 就是某些个别资源网失效了，没有，搜索不到这个资源网。这是第三方的问题，还是你这边可以修复的资源网？

这种情况属第三方来源站点失效，自行换源，站源会定期维护，不再做回复。
