### ISSUE TITLE
投屏功能

### ISSUE THREAD

**Issue by wangzechuang** [Jason-wam/Cat-Maven-2023#7]
无线投屏功能有bug，投不上去
![Screenshot_20230608_153733](https://github.com/Jason-wam/Cat-Maven-2023/assets/65115530/2ad2ebb0-fdd4-408f-ac5e-394bfddd0705)

**Comment by Jason-wam** [comment]
能搜索到设备吗

**Comment by Jason-wam** [comment]
按照错误日志来看的话是服务端异常，也就是电视端报的错误
